name: Feature request
description: Suggest an improvement.
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem should this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: This request does not require collecting analytics, telemetry, or sending Bankin headers to a third-party server.
          required: true
